name: "game_proxy"
mode: "dev"
port: 8082
app:
  #run-mode:debug/release
  run_mode: debug
  identity_key: idname

server:
  port: 8002
  read_timeout: 60
  write_timeout: 60

log:
  level: "debug"
  filename: "log/server.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  #host: "52.80.161.235"
  #host: "170.106.168.158"
  #port: 3306
  host: "gz-cdb-ffv1cc6n.sql.tencentcdb.com"
  port: 58934
  user: "miner"
  password: "tt2345678"
  db_name: "miner"
  db_type: mysql
  db_sslmode: ""
  db_path: ""
  max_open_conns: 10
  max_idle_conns: 5
mysql_log:
  host: "localhost"
  port: 3306
  #host: "gz-cdb-ffv1cc6n.sql.tencentcdb.com"
  #port: 58934
  user: "miner"
  password: "tt2345678"
  db_name: "miner_log"
  db_type: mysql
  db_sslmode: ""
  db_path: ""
  max_open_conns: 10
  max_idle_conns: 5
beego:
  #template_type: "xin"
  template_type: "cfmode"
  views_path: "gameServer/views;views"
  #template_type=admin
  #admin用户名 此用户登录不用认证
  admin_user: "admin"
  #域名白名单 白名单IP可以直接通过IP访问网站内容否则提示不能访问
  doman_white_list: "161.189.41.194"
  #默认需要认证模块
  not_auth_package: "public,static"
  #默认认证类型 0 不认证 1 登录认证 2 实时认证
  user_auth_type: 0
  #user_auth_type: 2
  #默认登录网关
  #auth_gateway: "/public/sign_in"
  auth_gateway: "/admin/"
  user_index: "/user/"
game_proxy:
  port: 7000
  #/*映射IP*/
  mapped_host: "127.0.0.1"
  mapped_port: 7300
game_server:
  is_save_package: true
